# Create a new user
# @name register

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.local",
  "userName": "Test Doe",
  "password": "123456"
}

###

# Login user by email and password
# @name login
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
"email": "user@test.local",
"password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/ 65ba5ac31adbe1ca4f089cd6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNWFjMzFhZGJlMWNhNGYwODljZDYiLCJlbWFpbCI6InVzZXJAdGVzdC5sb2NhbCIsInVzZXJOYW1lIjoiVGVzdCBEb2UiLCJhdmF0YXIiOiIiLCJpYXQiOjE3MDY3MTE3NTcsImV4cCI6MTcwNjcxMjM1N30.JxBBP0XBV2At1XTW3syMWtScmUnnhOrnHKRcTDgxY_4
Content-Type: application/json

###

# Change user password
POST http://localhost:3000/api/auth/update-password/65ba5ac31adbe1ca4f089cd6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNWFjMzFhZGJlMWNhNGYwODljZDYiLCJlbWFpbCI6InVzZXJAdGVzdC5sb2NhbCIsInVzZXJOYW1lIjoiVGVzdCBEb2UiLCJhdmF0YXIiOiIiLCJpYXQiOjE3MDY3MTE3NTcsImV4cCI6MTcwNjcxMjM1N30.JxBBP0XBV2At1XTW3syMWtScmUnnhOrnHKRcTDgxY_4
Content-Type: application/json

{
  "password": "123456",
  "newPassword": "1234567"
}

###

# Get new JWT pair
# @name refresh
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNWFjMzFhZGJlMWNhNGYwODljZDYiLCJlbWFpbCI6InVzZXJAdGVzdC5sb2NhbCIsInVzZXJOYW1lIjoiVGVzdCBEb2UiLCJhdmF0YXIiOiIiLCJ0b2tlbklkIjoiOGU4ZjJjODItZjg3ZC00Yjg4LTkwODgtZTkyYjcxZmE2NjViIiwiaWF0IjoxNzA2NzExNzU3LCJleHAiOjE3MDkzMDM3NTd9.FRjuA-Lq48oaIyrAW_nOeHklDkzpk-0rwXxw4fPRo8o

###
# Check token
# @name check
POST http://localhost:3000/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJhNWFjMzFhZGJlMWNhNGYwODljZDYiLCJlbWFpbCI6InVzZXJAdGVzdC5sb2NhbCIsInVzZXJOYW1lIjoiVGVzdCBEb2UiLCJhdmF0YXIiOiIiLCJpYXQiOjE3MDY3MTE4NzQsImV4cCI6MTcwNjcxMjQ3NH0.EA_dnOkX12eR3BQwVywf63aFOGeiBhfYr_GkocEjpKY

###
